/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Login: () => import('#controllers/login_controller'),
  Matches: () => import('#controllers/matches_controller'),
  movies: {
    Api: () => import('#controllers/movies/api_controller'),
    Movies: () => import('#controllers/movies/movies_controller'),
    Selects: () => import('#controllers/movies/selects_controller'),
  },
  Ratings: () => import('#controllers/ratings_controller'),
  watchlist: {
    Api: () => import('#controllers/watchlist/api_controller'),
    Home: () => import('#controllers/watchlist/home_controller'),
  },
}
