/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Login: () => import('#controllers/login_controller'),
  movies: {
    Finds: () => import('#controllers/movies/finds_controller'),
  },
  watchlist: {
    Home: () => import('#controllers/watchlist/home_controller'),
    Adds: () => import('#controllers/watchlist/adds_controller'),
  },
}
