/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GenreSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'tmdbId'] as const
  $columns = GenreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare tmdbId: number
}

export class MovieGenreSchema extends BaseModel {
  static $columns = ['genreId', 'movieId'] as const
  $columns = MovieGenreSchema.$columns
  @column()
  declare genreId: number
  @column({ isPrimary: true })
  declare movieId: number
}

export class MoviePickedResultSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'movieId', 'updatedAt'] as const
  $columns = MoviePickedResultSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare movieId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MovieSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'posterUrl', 'title', 'tmdbId', 'voteAverage'] as const
  $columns = MovieSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare posterUrl: string
  @column()
  declare title: string
  @column()
  declare tmdbId: number
  @column()
  declare voteAverage: number
}

export class RatingSchema extends BaseModel {
  static $columns = ['movieId', 'rating', 'userId'] as const
  $columns = RatingSchema.$columns
  @column({ isPrimary: true })
  declare movieId: number
  @column()
  declare rating: number | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'password'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
}

export class WatchlistItemSchema extends BaseModel {
  static $columns = ['createdAt', 'firstWatchedAt', 'lastWatched', 'movieId', 'userId', 'watched'] as const
  $columns = WatchlistItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare firstWatchedAt: DateTime | null
  @column.dateTime()
  declare lastWatched: DateTime | null
  @column()
  declare movieId: number
  @column()
  declare userId: number
  @column()
  declare watched: boolean
}
